# 项目相关配置
# Project related configuration
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.8.2
  # 版权年份
  copyrightYear: 2022
  # 实例演示开关
  # Example demo switch
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  # File path example (Windows configuration D:/ruoyi/uploadPath, Linux configuration /home/ruoyi/uploadPath)
  profile: D:/ruoyi/uploadPath
  uploadJpg : D:/ruoyi/uploadPath/upload/media/jpg
  # 获取ip地址开关
  # Get ip address switch
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  # verification code type math array calculation char character verification
  captchaType: math

# 开发环境配置
# Development environment configuration
server:
  # 服务器的HTTP端口，默认为8080
  # The HTTP port of the server, the default is 8080
  port: 8080
  servlet:
    # 应用的访问路径
    # The access path of the application
    context-path: /
  tomcat:
    # tomcat的URI编码
    # URI encoding of tomcat
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    # The number of queues after the number of connections is full, the default is 100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      # tomcat maximum number of threads, the default is 200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      # The number of threads Tomcat starts and initializes, the default value is 10
      min-spare: 100

# 日志配置
# log configuration
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# Spring配置
spring:
  # 资源信息
  # resource information
  messages:
    # 国际化资源文件路径
    # Internationalized resource file path
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  # File Upload
  servlet:
     multipart:
       # 单个文件大小
       # single file size
       max-file-size:  10MB
       # 设置总上传的文件大小
       # Set the total uploaded file size
       max-request-size:  20MB
  # 服务模块
  # service module
  devtools:
    restart:
      # 热部署开关
      # hot deploy switch
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        # Minimum idle connection in the connection pool
        min-idle: 0
        # 连接池中的最大空闲连接
        # Maximum idle connections in the connection pool
        max-idle: 8
        # 连接池的最大数据库连接数
        # The maximum number of database connections in the connection pool
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        # #Connection pool maximum blocking wait time (use a negative value to indicate no limit)
        max-wait: -1ms

# token配置
token:
    # 令牌自定义标识
    # token custom ID
    header: Authorization
    # 令牌密钥
    # token key
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）
    # Token validity period (default 30 minutes)
    expireTime: 30

# MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.ruoyi.project.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  # filter switch
  enabled: true
  # 排除链接（多个用逗号分隔）
  # Exclude links (multiple separated by commas)
  excludes: /system/notice
  # 匹配链接
  # match link
  urlPatterns: /system/*,/monitor/*,/tool/*

# 代码生成
# code generation
gen:
  # 作者
  author: ruoyi
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  # The default generated package path system needs to be changed to its own module name such as system monitor tool
  packageName: com.ruoyi.project.system
  # 自动去除表前缀，默认是true
  # Automatically remove table prefix, default is true
  autoRemovePre: false
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  # Table prefix (the generated class name will not contain the table prefix, multiple are separated by commas)
  tablePrefix: sys_