DELETE FROM `erp`.`sys_menu` WHERE (`menu_id` = '1100');
DELETE FROM `erp`.`sys_menu` WHERE (`menu_id` = '1101');
DELETE FROM `erp`.`sys_menu` WHERE (`menu_id` = '1102');
DELETE FROM `erp`.`sys_menu` WHERE (`menu_id` = '1103');
DELETE FROM `erp`.`sys_menu` WHERE (`menu_id` = '1104');
DELETE FROM `erp`.`sys_menu` WHERE (`menu_id` = '1105');

INSERT INTO `erp`.`sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `menu_name_en`, `menu_name_id`) VALUES ('1101', 'MBTI Test', '1078', '1', 'mbti', 'hr/mbti/index', '1', '0', 'C', '0', '0', 'hr:mbti:list', 'edit', 'admin', '2022-10-19 10:01:09', 'admin', '2022-10-19 10:15:56', 'MBTI Test菜单', 'MBTI Test', 'Tes MBTI');
INSERT INTO `erp`.`sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `remark`, `menu_name_en`, `menu_name_id`) VALUES ('1102', 'MBTI Test查询', '1101', '1', '#', '', '1', '0', 'F', '0', '0', 'hr:mbti:query', '#', 'admin', '2022-10-19 10:01:09', '', '', 'MBTI Test query', 'Kueri Tes MBTI');
INSERT INTO `erp`.`sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `remark`, `menu_name_en`, `menu_name_id`) VALUES ('1103', 'MBTI Test新增', '1101', '2', '#', '', '1', '0', 'F', '0', '0', 'hr:mbti:add', '#', 'admin', '2022-10-19 10:01:09', '', '', 'MBTI Test added', 'Tes MBTI ditambahkan');
INSERT INTO `erp`.`sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `remark`, `menu_name_en`, `menu_name_id`) VALUES ('1104', 'MBTI Test修改', '1101', '3', '#', '', '1', '0', 'F', '0', '0', 'hr:mbti:edit', '#', 'admin', '2022-10-19 10:01:09', '', '', 'MBTI Test Modification', 'Modifikasi Tes MBTI');
INSERT INTO `erp`.`sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `remark`, `menu_name_en`, `menu_name_id`) VALUES ('1105', 'MBTI Test删除', '1101', '4', '#', '', '1', '0', 'F', '0', '0', 'hr:mbti:remove', '#', 'admin', '2022-10-19 10:01:09', '', '', 'MBTI Test deleted', 'Tes MBTI dihapus');
INSERT INTO `erp`.`sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `remark`, `menu_name_en`, `menu_name_id`) VALUES ('1106', 'MBTI Test导出', '1101', '5', '#', '', '1', '0', 'F', '0', '0', 'hr:mbti:export', '#', 'admin', '2022-10-19 10:01:09', '', '', 'MBTI Test Export', 'Ekspor Tes MBTI');